
# subnets
#public_subnet: "10.18.0.0/24"
private_subnet: "10.135.0.0/16"

#firewall
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

# traefik vars
traefik_install_dir: /usr/bin
traefik_binary_url: https://github.com/containous/traefik/releases/download/v1.7.6/traefik_linux-amd64
traefik_bin_path: "{{ traefik_install_dir }}/traefik"
traefik_config_file: /etc/traefik.toml
acme_email: "hmj@goatpage.com"
main_domain: "hmzoo.org"
do_auth_token: "{{ lookup('env','DO_AUTH_TOKEN') }}"
traefik_template: "{{ playbook_dir }}/templates/traefik.toml"
traefik_systemd_unit_template: "{{ playbook_dir }}/templates/traefik.service"
traefik_systemd_unit_dest: /etc/systemd/system/traefik.service
traefik_http_port: 2020
traefik_basicauth: "{{ lookup('env','BASIC_AUTH') }}"

# gogs vars
gogs_user: git
gogs_user_home: /opt/git
gogs_binary_url: https://github.com/gogs/gogs/releases/download/v0.11.79/linux_amd64.zip
gogs_http_port: "3000"
gogs_use_mysql: false
gogs_db_name: gogs
gogs_db_username: gogs
gogs_db_password: root

#pip modules
pip_install_packages:
  - name: docker
  - name: docker-compose

#GOCD
sansible_gocd_server_dependencies_skip_java: yes
sansible_gocd_agent_dependencies_skip_java: yes
sansible_gocd_server_version: 19.*
sansible_gocd_server_passwd_users:
        hmj: "{{ lookup('env','GOCD_HMJ_PASSWD') }}"

#NODEJS
nodejs_npm_global_packages:
  - name: gatsby
